---

language: node_js

node_js:
  - 8

sudo: false

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  script:
    - yarn deploy

  on:
    branch: master
